import assert from "node:assert/strict";
import { execFileSync, spawnSync } from "node:child_process";
import { copyFile, mkdir, mkdtemp, readFile, symlink, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import test from "node:test";
const { renderProductBrief } = await import(new URL("../scripts/app-spec.mjs", import.meta.url).href) as {
  renderProductBrief: (spec: Record<string, unknown>) => string;
};

const productBrief = renderProductBrief({ app: { type: "dashboard", audience: "Analyste", decision: "Suivre les ventes", success: "Usage hebdomadaire" }, features: [] });

test("app doctor reports the next useful action without exposing environment values", async () => {
  const root = await mkdtemp(join(tmpdir(), "app-doctor-"));
  const files = [
    "config/data-projects.json",
    "config/genie-spaces.json",
    "scripts/app-doctor.mjs",
    "scripts/appkit-compatibility.mjs",
    "scripts/app-spec.mjs",
    "scripts/app-capabilities.mjs",
    "scripts/app-skills.mjs",
    "scripts/app-guide.mjs",
    "config/appkit-capabilities.json",
    "scripts/data-access.mjs",
    "scripts/data-preparation.mjs",
    "scripts/template-manifest.mjs",
    "scripts/template-status.mjs",
  ];
  for (const file of files) {
    const destination = join(root, file);
    await mkdir(dirname(destination), { recursive: true });
    await copyFile(file, destination);
  }
  await mkdir(join(root, "config"), { recursive: true });
  await mkdir(join(root, "data/contracts"), { recursive: true });
  await mkdir(join(root, "docs"), { recursive: true });
  await mkdir(join(root, "resources"), { recursive: true });
  await writeFile(
    join(root, "resources/data-access.generated.yml"),
    "# Generated by npm run data:access:render. Do not edit directly.\nresources:\n  apps:\n    app:\n      name: ${var.app_name}\n      description: ${var.app_description}\n      compute_size: MEDIUM\n      user_api_scopes:\n        - genie\n      permissions:\n        - group_name: ${var.can_manage_group}\n          level: CAN_MANAGE\n        - group_name: ${var.can_use_group}\n          level: CAN_USE\n      resources:\n        - name: sql-warehouse\n          sql_warehouse:\n            id: ${var.sql_warehouse_id}\n            permission: CAN_USE\n        - name: \"fraim-sales\"\n          genie_space:\n            name: \"Genie - FRAIM - Sales Performance\"\n            space_id: \"01f1706a44af166db267134b70dc27c8\"\n            permission: CAN_RUN\n",
    "utf8",
  );
  await writeFile(
    join(root, "data/resources.generated.yml"),
    "# Generated by npm run data:prepare:render. Do not edit directly.\nresources: {}\n",
    "utf8",
  );
  await writeFile(join(root, "package.json"), JSON.stringify({ name: "sample-app" }), "utf8");
  await writeFile(
    join(root, "config/app-spec.yml"),
    "version: 1\napp:\n  name: sample-app\n  type: dashboard\n  audience: Analyste\n  decision: Suivre les ventes\n  success: Usage hebdomadaire\nfeatures: []\n",
    "utf8",
  );
  await writeFile(join(root, "config/data-access.json"), JSON.stringify({ project: "dev-dtm-media-pm", sources: [] }), "utf8");
  await writeFile(
    join(root, "app.yaml"),
    "env:\n  - name: DATABRICKS_CATALOG\n    value: dev-dtm-media-pm\n  - name: DATABRICKS_GENIE_SPACE_ID_FRAIM_SALES\n    valueFrom: fraim-sales\n",
    "utf8",
  );
  await writeFile(
    join(root, ".env.example"),
    "DATABRICKS_CATALOG=dev-dtm-media-pm\nDATABRICKS_GENIE_SPACE_ID_FRAIM_SALES=01f1706a44af166db267134b70dc27c8\n",
    "utf8",
  );
  await writeFile(join(root, "docs/product-brief.md"), productBrief, "utf8");
  await symlink(join(process.cwd(), "node_modules"), join(root, "node_modules"), "dir");

  execFileSync(process.execPath, ["--input-type=module", "-e", 'import {renderDataAccess} from "./scripts/data-access.mjs"; await renderDataAccess({root:process.cwd()});'], { cwd: root });
  const command = spawnSync(process.execPath, ["scripts/app-doctor.mjs", "--json"], {
    cwd: root,
    encoding: "utf8",
    env: { ...process.env, PATH: "" },
  });
  assert.equal(command.status, 0, command.stderr);
  const results = JSON.parse(command.stdout) as Array<{ status: string; name: string; next?: string }>;
  assert.equal(results.some((item) => item.status === "fail"), false);
  assert.equal(results.find((item) => item.name === "Étape recommandée")?.next, "npm run data:init -- <nom>");
  assert.doesNotMatch(JSON.stringify(results), /DATABRICKS_TOKEN|CLIENT_SECRET/);
  assert.match(await readFile(join(root, "docs/product-brief.md"), "utf8"), /Suivre les ventes/);

  execFileSync(process.execPath, ["scripts/app-guide.mjs", "--non-interactive", "--type", "assistant", "--capabilities", "genie"], { cwd: root });
  const genieOnly = spawnSync(process.execPath, ["scripts/app-doctor.mjs", "--json"], { cwd: root, encoding: "utf8", env: { ...process.env, PATH: "" } });
  assert.equal(genieOnly.status, 0, genieOnly.stderr);
  const next = JSON.parse(genieOnly.stdout) as Array<{ name: string; next?: string }>;
  assert.equal(next.find((item) => item.name === "Étape recommandée")?.next, "npm run app:capabilities");
  assert.equal(next.some((item) => ["Première tranche", "Première source"].includes(item.name)), false);
});
