import assert from "node:assert/strict";
import { execFileSync, spawnSync } from "node:child_process";
import { copyFile, mkdir, mkdtemp, readFile, rm, symlink, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import test from "node:test";
import { parse } from "yaml";

const copiedFiles = [
  "config/data-projects.json",
  "config/genie-spaces.json",
  "scripts/app-spec.mjs",
  "scripts/app-capabilities.mjs",
  "scripts/app-skills.mjs",
  "config/appkit-capabilities.json",
  "docs/appkit-capabilities.md",
  ".agents/skills/create-analytics-dbx-app/references/appkit-capabilities.md",
  "scripts/data-access.mjs",
  "scripts/data-preparation.mjs",
  "scripts/init-app.mjs",
  "scripts/template-manifest.mjs",
  "template/manifest.yml",
];

const operationalFiles = [
  "package.json",
  "package-lock.json",
  ".env.example",
  "app.yaml",
  "databricks.yml",
  "data/databricks.yml",
  "data/resources.generated.yml",
  "config/app-spec.yml",
  "config/data-access.json",
  "config/genie-spaces.json",
  "config/data-projects.json",
  "docs/product-brief.md",
  "resources/data-access.generated.yml",
  ".github/workflows/deploy.yml",
  ".valiuz-template.yml",
];

type TemplateManifest = {
  template: { currentVersion: string };
  versions: Record<string, { extends?: string; capabilities: string[] }>;
};

function expectedCapabilities(manifest: TemplateManifest, version: string): string[] {
  const release = manifest.versions[version];
  assert.ok(release, `Template release ${version} must exist.`);
  const inherited = release.extends ? expectedCapabilities(manifest, release.extends) : [];
  return [...new Set([...inherited, ...release.capabilities])];
}

async function prepareRoot(prefix: string): Promise<string> {
  const root = await mkdtemp(join(tmpdir(), prefix));
  for (const file of copiedFiles) {
    const destination = join(root, file);
    await mkdir(dirname(destination), { recursive: true });
    await copyFile(file, destination);
  }
  const fixtures: Record<string, string> = {
    "package.json": JSON.stringify({ name: "__PACKAGE_NAME__", version: "0.1.0" }, null, 2),
    "package-lock.json": JSON.stringify({ name: "__PACKAGE_NAME__", version: "0.1.0", lockfileVersion: 3, packages: { "": { name: "__PACKAGE_NAME__", version: "0.1.0" } } }, null, 2),
    ".env.example": "APP_NAME=\"__APP_NAME__\"\nAPP_DESCRIPTION=\"__APP_DESCRIPTION__\"\nAPP_SUPPORT_NAME=\"__APP_SUPPORT_NAME__\"\nAPP_SUPPORT_SLACK_URL=\"__APP_SUPPORT_SLACK_URL__\"\nDATABRICKS_HOST=https://3070470996474403.3.gcp.databricks.com\nDATABRICKS_CONFIG_PROFILE=valiuz-analytics-dev\nDATABRICKS_SQL_WAREHOUSE_ID=ab362e9710498a08\nDATABRICKS_GENIE_SPACE_ID_FRAIM_SALES=01f1706a44af166db267134b70dc27c8\nDATABRICKS_CATALOG=__DATABRICKS_CATALOG__\nDATABRICKS_SCHEMA=__DATABRICKS_SCHEMA__\n",
    "app.yaml": "env:\n  - name: APP_NAME\n    value: \"__APP_NAME__\"\n  - name: APP_DESCRIPTION\n    value: \"__APP_DESCRIPTION__\"\n  - name: APP_SUPPORT_NAME\n    value: \"__APP_SUPPORT_NAME__\"\n  - name: APP_SUPPORT_SLACK_URL\n    value: \"__APP_SUPPORT_SLACK_URL__\"\n  - name: DATABRICKS_GENIE_SPACE_ID_FRAIM_SALES\n    valueFrom: fraim-sales\n  - name: DATABRICKS_CATALOG\n    value: \"__DATABRICKS_CATALOG__\"\n  - name: DATABRICKS_SCHEMA\n    value: \"__DATABRICKS_SCHEMA__\"\n",
    "databricks.yml": "bundle:\n  name: \"__APP_NAME__\"\nvariables:\n  app_description:\n    default: \"__APP_DESCRIPTION__\"\n  sql_warehouse_id:\n    default: ab362e9710498a08\n  git_repo_url:\n    default: \"__GIT_REPOSITORY_URL__\"\n  can_use_group:\n    default: \"__CAN_USE_GROUP__\"\n  can_manage_group:\n    default: \"__CAN_MANAGE_GROUP__\"\n  prod_root_path:\n    default: \"__DATABRICKS_PROD_ROOT_PATH__\"\ntargets:\n  prod:\n    workspace:\n      host: https://3070470996474403.3.gcp.databricks.com\n",
    "data/databricks.yml": "bundle:\n  name: \"__APP_NAME__-data\"\nvariables:\n  sql_warehouse_id:\n    default: ab362e9710498a08\ntargets:\n  prod:\n    workspace:\n      host: https://3070470996474403.3.gcp.databricks.com\n      root_path: \"__DATABRICKS_PROD_ROOT_PATH__/data\"\n",
    "data/resources.generated.yml": "# Generated by npm run data:prepare:render. Do not edit directly.\nresources: {}\n",
    "config/app-spec.yml": "version: 1\napp:\n  name: __PACKAGE_NAME__\n  type: dashboard\n  audience: À confirmer\n  decision: À confirmer\n  success: À confirmer\nfeatures: []\n",
    "config/data-access.json": "{\n  \"project\": \"__DATABRICKS_CATALOG__\",\n  \"sources\": []\n}\n",
    "docs/product-brief.md": "",
    "resources/data-access.generated.yml": "# Generated by npm run data:access:render. Do not edit directly.\nresources:\n  apps:\n    app:\n      name: ${var.app_name}\n      description: ${var.app_description}\n      compute_size: MEDIUM\n      permissions:\n        - group_name: ${var.can_manage_group}\n          level: CAN_MANAGE\n        - group_name: ${var.can_use_group}\n          level: CAN_USE\n      resources:\n        - name: sql-warehouse\n          sql_warehouse:\n            id: ${var.sql_warehouse_id}\n            permission: CAN_USE\n",
    ".github/workflows/deploy.yml": "env:\n  APP_NAME: \"__APP_NAME__\"\n",
  };
  for (const [file, content] of Object.entries(fixtures)) {
    const destination = join(root, file);
    await mkdir(dirname(destination), { recursive: true });
    await writeFile(destination, `${content}\n`, "utf8");
  }
  await mkdir(join(root, "data/contracts"), { recursive: true });
  await symlink(join(process.cwd(), "node_modules"), join(root, "node_modules"), "dir");
  return root;
}

test("bootstrap replaces all operational placeholders and keeps JSON valid", async () => {
  const root = await prepareRoot("databricks-app-init-");

  execFileSync(
    process.execPath,
    [
      "scripts/init-app.mjs",
      "sample-app",
      "--non-interactive",
      "--description", "Sample analytics app",
      "--support-name", "Alexis",
      "--support-slack-url", "https://valiuz.slack.com/team/U123456",
      "--warehouse", "warehouse-123",
      "--data-project", "dev-dtm-media-pm",
      "--schema", "sample_app",
      "--host", "https://dbc.example.cloud.databricks.com",
      "--repository-url", "https://github.com/example/sample-app",
      "--can-use-group", "analysts",
      "--can-manage-group", "app-admins",
    ],
    { cwd: root },
  );

  const rendered = await Promise.all(operationalFiles.map((file) => readFile(join(root, file), "utf8")));
  const renderedText = rendered.join("\n");
  assert.doesNotMatch(renderedText, /__[A-Z][A-Z_]+__/);
  assert.doesNotMatch(renderedText, /3070470996474403\.3\.gcp\.databricks\.com/);
  assert.doesNotMatch(renderedText, /ab362e9710498a08/);
  assert.match(renderedText, /sample-app/);
  assert.match(renderedText, /https:\/\/dbc\.example\.cloud\.databricks\.com/);
  assert.match(renderedText, /warehouse-123/);
  assert.match(renderedText, /dev-dtm-media-pm/);
  assert.match(renderedText, /Alexis/);
  assert.match(renderedText, /https:\/\/valiuz\.slack\.com\/team\/U123456/);
  JSON.parse(await readFile(join(root, "package.json"), "utf8"));
  JSON.parse(await readFile(join(root, "package-lock.json"), "utf8"));
  const templateState = parse(await readFile(join(root, ".valiuz-template.yml"), "utf8"));
  const manifest = parse(await readFile("template/manifest.yml", "utf8")) as TemplateManifest;
  assert.equal(templateState.template.version, manifest.template.currentVersion);
  assert.deepEqual(templateState.capabilities, expectedCapabilities(manifest, manifest.template.currentVersion));
  assert.deepEqual(templateState.appliedUpgrades, []);
});

test("bootstrap refuses to reinitialize an app or reset its migration history before prompting or writing", async (t) => {
  const root = await prepareRoot("databricks-app-resume-");
  t.after(() => rm(root, { recursive: true, force: true }));
  execFileSync(process.execPath, ["scripts/init-app.mjs", "existing-app", "--non-interactive"], { cwd: root });
  const statePath = join(root, ".valiuz-template.yml");
  const state = await readFile(statePath, "utf8");
  const paths = [...operationalFiles, ".valiuz-template.yml"];
  const before = await Promise.all(paths.map((path) => readFile(join(root, path), "utf8")));
  const result = spawnSync(process.execPath, ["scripts/init-app.mjs", "another-name"], { cwd: root, encoding: "utf8", timeout: 5000 });
  assert.equal(result.status, 1);
  assert.match(result.stderr, /déjà initialisée/);
  assert.deepEqual(await Promise.all(paths.map((path) => readFile(join(root, path), "utf8"))), before);
  assert.equal(await readFile(statePath, "utf8"), state);
  // A tracked state also blocks initialization if someone has restored the package placeholder.
  const pkg = JSON.parse(await readFile(join(root, "package.json"), "utf8"));
  await writeFile(join(root, "package.json"), JSON.stringify({ ...pkg, name: "__PACKAGE_NAME__" }));
  assert.equal(spawnSync(process.execPath, ["scripts/init-app.mjs", "another-name", "--non-interactive"], { cwd: root }).status, 1);
  assert.equal(await readFile(statePath, "utf8"), state);
});

test("bootstrap uses the shared Valiuz workspace and SQL warehouse defaults", async () => {
  const root = await prepareRoot("databricks-app-defaults-");

  execFileSync(
    process.execPath,
    [
      "scripts/init-app.mjs",
      "sample-app",
      "--non-interactive",
      "--schema", "sample_app",
    ],
    { cwd: root },
  );

  const environment = await readFile(join(root, ".env.example"), "utf8");
  const bundle = await readFile(join(root, "databricks.yml"), "utf8");
  const dataResources = await readFile(join(root, "resources/data-access.generated.yml"), "utf8");
  const renderedText = `${environment}\n${bundle}\n${dataResources}`;
  assert.match(renderedText, /https:\/\/3070470996474403\.3\.gcp\.databricks\.com/);
  assert.match(renderedText, /ab362e9710498a08/);
  assert.match(environment, /DATABRICKS_CONFIG_PROFILE=valiuz-analytics-dev/);
  assert.match(environment, /DATABRICKS_CATALOG=dev-dtm-operating/);
  assert.match(environment, /DATABRICKS_GENIE_SPACE_ID_FRAIM_SALES=01f1706a44af166db267134b70dc27c8/);
  assert.match(environment, /APP_SUPPORT_NAME="Alexis"/);
  assert.match(environment, /APP_SUPPORT_SLACK_URL="https:\/\/valiuz\.slack\.com\/team\/U01C3FT98HE"/);
  assert.match(dataResources, /permission: CAN_USE/);
  assert.match(dataResources, /user_api_scopes:\n\s+- genie/);
  assert.match(dataResources, /permission: CAN_RUN/);
});

test("bootstrap rejects a support link outside Valiuz Slack", async () => {
  const root = await prepareRoot("databricks-app-invalid-support-");

  assert.throws(
    () =>
      execFileSync(
        process.execPath,
        [
          "scripts/init-app.mjs",
          "sample-app",
          "--non-interactive",
          "--support-slack-url", "https://example.com/support",
        ],
        { cwd: root, stdio: "pipe" },
      ),
    /Command failed/,
  );
});

test("bootstrap rejects a data project outside the Valiuz allowlist", async () => {
  const root = await prepareRoot("databricks-app-invalid-project-");

  assert.throws(
    () =>
      execFileSync(
        process.execPath,
        [
          "scripts/init-app.mjs",
          "sample-app",
          "--non-interactive",
          "--data-project", "unmanaged-project",
          "--schema", "sample_app",
        ],
        { cwd: root, stdio: "pipe" },
      ),
    /Command failed/,
  );
});

test("bootstrap help exits without prompting or changing the copied application", async (t) => {
  const root = await prepareRoot("databricks-app-help-");
  t.after(() => rm(root, { recursive: true, force: true }));
  const paths = operationalFiles.filter((file) => file !== ".valiuz-template.yml");
  const before = await Promise.all(paths.map((file) => readFile(join(root, file), "utf8")));
  const output = execFileSync(process.execPath, ["scripts/init-app.mjs", "--help"], { cwd: root, encoding: "utf8", timeout: 5000 });
  assert.match(output, /Usage: npm run init-app/);
  assert.deepEqual(await Promise.all(paths.map((file) => readFile(join(root, file), "utf8"))), before);
  await assert.rejects(readFile(join(root, ".valiuz-template.yml")), { code: "ENOENT" });
});
