import assert from "node:assert/strict";
import { execFileSync, spawnSync } from "node:child_process";
import { copyFile, mkdir, mkdtemp, symlink, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import test from "node:test";
const { renderProductBrief } = await import(new URL("../scripts/app-spec.mjs", import.meta.url).href) as {
  renderProductBrief: (spec: Record<string, unknown>) => string;
};

const productBrief = renderProductBrief({ app: { type: "dashboard", audience: "Analyste", decision: "Suivre les ventes", success: "Usage hebdomadaire" }, features: [] });

test("real preview requires an explicit confirmation before remote changes", async () => {
  const root = await mkdtemp(join(tmpdir(), "preview-real-"));
  const files = [
    "config/data-projects.json",
    "config/genie-spaces.json",
    "scripts/app-doctor.mjs",
    "scripts/appkit-compatibility.mjs",
    "scripts/template-manifest.mjs",
    "scripts/template-status.mjs",
    "scripts/app-spec.mjs",
    "scripts/app-capabilities.mjs",
    "scripts/app-skills.mjs",
    "config/appkit-capabilities.json",
    "scripts/data-access.mjs",
    "scripts/data-preparation.mjs",
    "scripts/preview-real.mjs",
  ];
  for (const file of files) {
    const destination = join(root, file);
    await mkdir(dirname(destination), { recursive: true });
    await copyFile(file, destination);
  }
  await mkdir(join(root, "config"), { recursive: true });
  await mkdir(join(root, "data/contracts"), { recursive: true });
  await mkdir(join(root, "docs"), { recursive: true });
  await mkdir(join(root, "resources"), { recursive: true });
  await writeFile(
    join(root, "resources/data-access.generated.yml"),
    "# Generated by npm run data:access:render. Do not edit directly.\nresources:\n  apps:\n    app:\n      name: ${var.app_name}\n      description: ${var.app_description}\n      compute_size: MEDIUM\n      user_api_scopes:\n        - genie\n      permissions:\n        - group_name: ${var.can_manage_group}\n          level: CAN_MANAGE\n        - group_name: ${var.can_use_group}\n          level: CAN_USE\n      resources:\n        - name: sql-warehouse\n          sql_warehouse:\n            id: ${var.sql_warehouse_id}\n            permission: CAN_USE\n        - name: \"fraim-sales\"\n          genie_space:\n            name: \"Genie - FRAIM - Sales Performance\"\n            space_id: \"01f1706a44af166db267134b70dc27c8\"\n            permission: CAN_RUN\n",
    "utf8",
  );
  await writeFile(
    join(root, "data/resources.generated.yml"),
    "# Generated by npm run data:prepare:render. Do not edit directly.\nresources: {}\n",
    "utf8",
  );
  await writeFile(join(root, "package.json"), JSON.stringify({ name: "sample-app" }), "utf8");
  await writeFile(
    join(root, "config/app-spec.yml"),
    "version: 1\napp:\n  name: sample-app\n  type: dashboard\n  audience: Analyste\n  decision: Suivre les ventes\n  success: Usage hebdomadaire\nfeatures: []\n",
    "utf8",
  );
  await writeFile(join(root, "config/data-access.json"), JSON.stringify({ project: "dev-dtm-media-pm", sources: [] }), "utf8");
  await writeFile(
    join(root, "app.yaml"),
    "env:\n  - name: DATABRICKS_CATALOG\n    value: dev-dtm-media-pm\n  - name: DATABRICKS_GENIE_SPACE_ID_FRAIM_SALES\n    valueFrom: fraim-sales\n",
    "utf8",
  );
  await writeFile(
    join(root, ".env.example"),
    "DATABRICKS_CATALOG=dev-dtm-media-pm\nDATABRICKS_GENIE_SPACE_ID_FRAIM_SALES=01f1706a44af166db267134b70dc27c8\n",
    "utf8",
  );
  await writeFile(join(root, "docs/product-brief.md"), productBrief, "utf8");
  await symlink(join(process.cwd(), "node_modules"), join(root, "node_modules"), "dir");

  execFileSync(process.execPath, ["--input-type=module", "-e", 'import { renderDataAccess } from "./scripts/data-access.mjs"; await renderDataAccess({ root: process.cwd() });'], { cwd: root });

  const result = spawnSync(process.execPath, ["scripts/preview-real.mjs"], {
    cwd: root,
    encoding: "utf8",
    env: { ...process.env, PATH: "" },
  });
  assert.equal(result.status, 2, result.stderr);
  assert.match(result.stdout, /No remote change made/);
  assert.doesNotMatch(result.stdout, /bundle deploy/);

  await writeFile(
    join(root, "config/data-access.json"),
    JSON.stringify({
      project: "dev-dtm-media-pm",
      sources: [
        {
          name: "history",
          fullName: "dev-dtm-media-pm.analytics.history",
          purpose: "Validate explicit replay dates",
        },
      ],
    }),
    "utf8",
  );
  await writeFile(
    join(root, "data/contracts/history.yml"),
    [
      "version: 1",
      "name: history",
      "mode: notebook",
      "appSource: history",
      "source: dev-dtm-media-pm.raw.sales",
      "output: dev-dtm-media-pm.analytics.history",
      "columns: [sale_date, store_id, revenue]",
      "owner: Analytics",
      "purpose: Validate explicit replay dates",
      "grain: One row per date and store",
      "keys: [sale_date, store_id]",
      "refresh: manual",
      "freshnessHours: 24",
      "timeoutMinutes: 60",
      "replay:",
      "  strategy: bounded-replace",
      "  dateColumn: sale_date",
      "  defaultLookbackDays: 7",
      "  maxDays: 31",
      "  finalizationLagDays: 1",
      "  requiredHistoryDays: 365",
      "  outputRetentionDays: 365",
      "  sourceRetentionDays: 730",
      "",
    ].join("\n"),
    "utf8",
  );
  const bounded = spawnSync(process.execPath, ["scripts/preview-real.mjs", "--prepare-data"], {
    cwd: root,
    encoding: "utf8",
    env: { ...process.env, PATH: "" },
  });
  assert.equal(bounded.status, 1);
  assert.match(bounded.stderr, /cannot choose replay dates for bounded datasets/);
});
